apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volumes
  labels:
    app: shared-volumes
spec:
  capacity:
    storage: 100Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hallm-shared
  hostPath:
    path: /var/lib/hallm/shared
    type: DirectoryOrCreate
  claimRef:
    namespace: default
    name: shared-volumes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volumes
  namespace: default
spec:
  accessModes: [ReadWriteMany]
  storageClassName: hallm-shared
  resources:
    requests:
      storage: 100Gi
  volumeName: shared-volumes

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volumes
  labels:
    app: config-volumes
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hallm-config
  hostPath:
    path: /var/lib/hallm/config
    type: DirectoryOrCreate
  claimRef:
    namespace: default
    name: config-volumes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volumes
  namespace: default
spec:
  accessModes: [ReadWriteMany]
  storageClassName: hallm-config
  resources:
    requests:
      storage: 20Gi
  volumeName: config-volumes
